In [ ]:
#importing the required libarires
import numpy as np
import pandas as pd

In [ ]:
print(1e-4)

0.0001


In [ ]:
#create class for avoid repetation of code

class Perceptron:
  def __init__(self, eta, epochs):
    #weights = 3 because the perceptron model is designed to work with input data that has three features
    self.weights = np.random.randn(3) * 1e-4
    print(f"self.weights : {self.weights}")

    self.eta = eta #eta is learning rate
    self.epochs = epochs #epochs is iteration of weight updations


  def activationFunction(self, inputs, weights):
    z = np.dot(inputs, weights)
    return np.where(z > 0, 1, 0)

  def fit(self, X, y):
    self.X = X
    self.y = y


    #Including a bias term allows the perceptron to capture patterns that don't necessarily pass through the origin (0,0) in the input space.
    X_with_bias = np.c_[self.X, -np.ones((len(self.X), 1))]
    print(f"X_with_bias : {X_with_bias}")

    for epoch in range(self.epochs):
      print(f"For epoch : {epoch}")
      y_hat = self.activationFunction(X_with_bias, self.weights)
      print(f"predicted values : \n{y_hat}")

      error = self.y - y_hat
      print(f"error : \n{error}")

      #weight updation formula :
      self.weights = self.weights + self.eta * np.dot(X_with_bias.T, error)
      print(f"Updated weights : \n{self.weights}")

  def predict(self, X):
      X_with_bias = np.c_[X, -np.ones((len(self.X), 1))]
      return self.activationFunction(X_with_bias, self.weights)

## Using AND GATE

In [ ]:
#create the data
data = {"x1" : [0, 0, 1, 1], "x2" : [0, 1, 0, 1], "y" : [0, 0, 0, 1]}

AND = pd.DataFrame(data)
AND

x1  x2  y
0   0   0  0
1   0   1  0
2   1   0  0
3   1   1  1

In [ ]:
X = AND.drop("y", axis = 1)
X

x1  x2
0   0   0
1   0   1
2   1   0
3   1   1

In [ ]:
y = AND["y"]
y.to_frame()

y
0  0
1  0
2  0
3  1

In [ ]:
model = Perceptron(eta = 0.5, epochs = 10)
model.fit(X, y)

self.weights : [ 3.65279019e-05  4.56095965e-06 -1.41992718e-04]
X_with_bias : [[ 0.  0. -1.]
 [ 0.  1. -1.]
 [ 1.  0. -1.]
 [ 1.  1. -1.]]
For epoch : 0
predicted values : 
[1 1 1 1]
error : 
0   -1
1   -1
2   -1
3    0
Name: y, dtype: int64
Updated weights : 
[-0.49996347 -0.49999544  1.49985801]
For epoch : 1
predicted values : 
[0 0 0 0]
error : 
0    0
1    0
2    0
3    1
Name: y, dtype: int64
Updated weights : 
[3.65279019e-05 4.56095965e-06 9.99858007e-01]
For epoch : 2
predicted values : 
[0 0 0 0]
error : 
0    0
1    0
2    0
3    1
Name: y, dtype: int64
Updated weights : 
[0.50003653 0.50000456 0.49985801]
For epoch : 3
predicted values : 
[0 1 1 1]
error : 
0    0
1   -1
2   -1
3    0
Name: y, dtype: int64
Updated weights : 
[3.65279019e-05 4.56095965e-06 1.49985801e+00]
For epoch : 4
predicted values : 
[0 0 0 0]
error : 
0    0
1    0
2    0
3    1
Name: y, dtype: int64
Updated weights : 
[0.50003653 0.50000456 0.99985801]
For epoch : 5
predicted values : 
[0 0 0 1]
erro

In [ ]:
model.predict(X)

array([0, 0, 0, 1])

In [ ]:
model.weights

array([0.50003653, 0.50000456, 0.99985801])

## Using OR GATE

In [ ]:
#create the data
data = {"x1" : [0, 0, 1, 1], "x2" : [0, 1, 0, 1], "y" : [0, 1, 1, 1]}

OR = pd.DataFrame(data)
OR

x1  x2  y
0   0   0  0
1   0   1  1
2   1   0  1
3   1   1  1

In [ ]:
X = OR.drop("y", axis = 1)
X

x1  x2
0   0   0
1   0   1
2   1   0
3   1   1

In [ ]:
y = OR.y
y.to_frame()

y
0  0
1  1
2  1
3  1

In [ ]:
model = Perceptron(eta = 0.5, epochs = 10)
model.fit(X, y)

self.weights : [ 8.33657614e-05  1.99110831e-05 -4.95551637e-06]
X_with_bias : [[ 0.  0. -1.]
 [ 0.  1. -1.]
 [ 1.  0. -1.]
 [ 1.  1. -1.]]
For epoch : 0
predicted values : 
[1 1 1 1]
error : 
0   -1
1    0
2    0
3    0
Name: y, dtype: int64
Updated weights : 
[8.33657614e-05 1.99110831e-05 4.99995044e-01]
For epoch : 1
predicted values : 
[0 0 0 0]
error : 
0    0
1    1
2    1
3    1
Name: y, dtype: int64
Updated weights : 
[ 1.00008337  1.00001991 -1.00000496]
For epoch : 2
predicted values : 
[1 1 1 1]
error : 
0   -1
1    0
2    0
3    0
Name: y, dtype: int64
Updated weights : 
[ 1.00008337  1.00001991 -0.50000496]
For epoch : 3
predicted values : 
[1 1 1 1]
error : 
0   -1
1    0
2    0
3    0
Name: y, dtype: int64
Updated weights : 
[ 1.00008337e+00  1.00001991e+00 -4.95551637e-06]
For epoch : 4
predicted values : 
[1 1 1 1]
error : 
0   -1
1    0
2    0
3    0
Name: y, dtype: int64
Updated weights : 
[1.00008337 1.00001991 0.49999504]
For epoch : 5
predicted values : 
[0 1 1 1

In [ ]:
model.predict(X)

array([0, 1, 1, 1])

In [ ]:
model.weights

array([1.00008337, 1.00001991, 0.49999504])

## Using XOR GATE
- it is complex gate type, so perceptron are not familiar with complex relationship of models.

In [ ]:
#create the data
data = {"x1" : [0, 0, 1, 1], "x2" : [0, 1, 0, 1], "y" : [0, 1, 1, 0]}

XOR = pd.DataFrame(data)
XOR

x1  x2  y
0   0   0  0
1   0   1  1
2   1   0  1
3   1   1  0

In [ ]:
X = XOR.drop("y", axis = 1)
X

x1  x2
0   0   0
1   0   1
2   1   0
3   1   1

In [ ]:
y = XOR.y
y.to_frame()

y
0  0
1  1
2  1
3  0

In [ ]:
model = Perceptron(0.5, 100)
model.fit(X, y)

self.weights : [ 3.99145276e-05 -3.13659963e-05  2.41965449e-05]
X_with_bias : [[ 0.  0. -1.]
 [ 0.  1. -1.]
 [ 1.  0. -1.]
 [ 1.  1. -1.]]
For epoch : 0
predicted values : 
[0 0 1 0]
error : 
0    0
1    1
2    0
3    0
Name: y, dtype: int64
Updated weights : 
[ 3.99145276e-05  4.99968634e-01 -4.99975803e-01]
For epoch : 1
predicted values : 
[1 1 1 1]
error : 
0   -1
1    0
2    0
3   -1
Name: y, dtype: int64
Updated weights : 
[-4.99960085e-01 -3.13659963e-05  5.00024197e-01]
For epoch : 2
predicted values : 
[0 0 0 0]
error : 
0    0
1    1
2    1
3    0
Name: y, dtype: int64
Updated weights : 
[ 3.99145276e-05  4.99968634e-01 -4.99975803e-01]
For epoch : 3
predicted values : 
[1 1 1 1]
error : 
0   -1
1    0
2    0
3   -1
Name: y, dtype: int64
Updated weights : 
[-4.99960085e-01 -3.13659963e-05  5.00024197e-01]
For epoch : 4
predicted values : 
[0 0 0 0]
error : 
0    0
1    1
2    1
3    0
Name: y, dtype: int64
Updated weights : 
[ 3.99145276e-05  4.99968634e-01 -4.99975803e-01]


In [ ]:
model.predict(X)

array([0, 0, 0, 0])

Here, we can find that the model is not accessable for finding the complex relationship between the datasets

- predicted output = array([0, 0, 0, 0])
- actual output required = array([0, 1, 1, 0])

But, we can find them by using some changes.

In [ ]:
model.weights

array([-4.99960085e-01, -3.13659963e-05,  5.00024197e-01])

In [ ]:
#import the libararies
import numpy as np
from sklearn.datasets import load_iris
from sklearn.linear_model import Perceptron

In [ ]:
iris = load_iris()
iris

{'data': array([[5.1, 3.5, 1.4, 0.2],
        [4.9, 3. , 1.4, 0.2],
        [4.7, 3.2, 1.3, 0.2],
        [4.6, 3.1, 1.5, 0.2],
        [5. , 3.6, 1.4, 0.2],
        [5.4, 3.9, 1.7, 0.4],
        [4.6, 3.4, 1.4, 0.3],
        [5. , 3.4, 1.5, 0.2],
        [4.4, 2.9, 1.4, 0.2],
        [4.9, 3.1, 1.5, 0.1],
        [5.4, 3.7, 1.5, 0.2],
        [4.8, 3.4, 1.6, 0.2],
        [4.8, 3. , 1.4, 0.1],
        [4.3, 3. , 1.1, 0.1],
        [5.8, 4. , 1.2, 0.2],
        [5.7, 4.4, 1.5, 0.4],
        [5.4, 3.9, 1.3, 0.4],
        [5.1, 3.5, 1.4, 0.3],
        [5.7, 3.8, 1.7, 0.3],
        [5.1, 3.8, 1.5, 0.3],
        [5.4, 3.4, 1.7, 0.2],
        [5.1, 3.7, 1.5, 0.4],
        [4.6, 3.6, 1. , 0.2],
        [5.1, 3.3, 1.7, 0.5],
        [4.8, 3.4, 1.9, 0.2],
        [5. , 3. , 1.6, 0.2],
        [5. , 3.4, 1.6, 0.4],
        [5.2, 3.5, 1.5, 0.2],
        [5.2, 3.4, 1.4, 0.2],
        [4.7, 3.2, 1.6, 0.2],
        [4.8, 3.1, 1.6, 0.2],
        [5.4, 3.4, 1.5, 0.4],
        [5.2, 4.1, 1.5, 0.1],
  

In [ ]:
X = iris.data[:, (2, 3)]
X

array([[1.4, 0.2],
       [1.4, 0.2],
       [1.3, 0.2],
       [1.5, 0.2],
       [1.4, 0.2],
       [1.7, 0.4],
       [1.4, 0.3],
       [1.5, 0.2],
       [1.4, 0.2],
       [1.5, 0.1],
       [1.5, 0.2],
       [1.6, 0.2],
       [1.4, 0.1],
       [1.1, 0.1],
       [1.2, 0.2],
       [1.5, 0.4],
       [1.3, 0.4],
       [1.4, 0.3],
       [1.7, 0.3],
       [1.5, 0.3],
       [1.7, 0.2],
       [1.5, 0.4],
       [1. , 0.2],
       [1.7, 0.5],
       [1.9, 0.2],
       [1.6, 0.2],
       [1.6, 0.4],
       [1.5, 0.2],
       [1.4, 0.2],
       [1.6, 0.2],
       [1.6, 0.2],
       [1.5, 0.4],
       [1.5, 0.1],
       [1.4, 0.2],
       [1.5, 0.2],
       [1.2, 0.2],
       [1.3, 0.2],
       [1.4, 0.1],
       [1.3, 0.2],
       [1.5, 0.2],
       [1.3, 0.3],
       [1.3, 0.3],
       [1.3, 0.2],
       [1.6, 0.6],
       [1.9, 0.4],
       [1.4, 0.3],
       [1.6, 0.2],
       [1.4, 0.2],
       [1.5, 0.2],
       [1.4, 0.2],
       [4.7, 1.4],
       [4.5, 1.5],
       [4.9,

In [ ]:
y = (iris.target == 0).astype("int")
y

array([1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [ ]:
#create the model
model = Perceptron()

#fit the model with X and y
model.fit(X, y)

Perceptron()

In [ ]:
model.predict([[2, 0.5]])

array([0])

In [ ]:
model.predict([[1.4, 0.5]])

array([1])